version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inventory-control
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata: